import {theme} from "@/styles";
import { GlobalStyles } from "@/styles/global";
//import {Container} from "@/app/styles";
// import Header from "@/app/components/header/header";
import {DataProvider, useData} from "@/context/DataContext";
import {AppContainer} from "@/app/styles";
import {ThemeProvider} from "styled-components";
import Providers from "@/providers";
import Header from "@/app/components/header/header";
import CartDetails from "@/app/components/cartDetails/cartDetails";



export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous"/>
        <link
            href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:ital,wght@0,100..900;1,100..900&family=Roboto:wght@400;700&display=swap"
            rel="stylesheet"
        />

      </head>
      <body>
      <DataProvider>
        <Providers>
            <AppContainer>
                <Header/>
                <CartDetails/>
              {children}
            </AppContainer>
        </Providers>
      </DataProvider>

      </body>

      </html>
  )
}
